/****************************************************
** RISC-V_L_instr.sv
** Author: Kai Roy
** Version: 1.0
** Date: 7/10/2024
** Description: 
** Module for Store instructions - data to be written to reg file is generated by this module
****************************************************/
// !!! Verify what this module does !!!

// `timescale 1ns / 1ps
`timescale 1ns / 1ns
import riscv_pkg::*;


module L_type(Instr_IO_cpu_sig.L_type_io_ports bus);
    logic [31:0] instr;
    logic [31:0] daddr;
    logic [31:0] drdata;
    logic [31:0] out;
	logic [31:0] offset;


	assign instr	= bus.idata[14:12];
	assign daddr	= bus.daddr;
	assign drdata	= bus.drdata;

	assign bus.regdata_L = out;

	l_func func;
	assign func = l_func'(instr);

	 
    always_comb begin
        offset = (daddr[1:0] << 3);

		unique case (func)
			LB:		out = {{24{drdata[offset+7]}}, drdata[offset +: 8]};
			LH:		out = {{16{drdata[offset+15]}}, drdata[offset +: 16]};
			LW:		out = drdata;
			LBU:	out = {24'b0, drdata[offset +: 8]};
			LHU:	out = {16'b0, drdata[offset +: 16]};
			default: ;
		endcase
    end
endmodule
